# Generated by Django 6.0.7 on 2026-07-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('born_date', models.DateField()),
                ('nationality', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'student',
                'db_table_comment': 'test meta data for student model',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('category', models.CharField()),
            ],
        ),
    ]
