# Generated by Django 6.0.7 on 2026-07-20 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 20, 9, 4, 47, 242923)),
        ),
        migrations.AddField(
            model_name='student',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deleted_at'),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
        migrations.AddField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 20, 9, 4, 47, 243599)),
        ),
        migrations.AddField(
            model_name='subject',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deleted_at'),
        ),
        migrations.AddField(
            model_name='subject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
    ]
