# Generated by Django 6.0.7 on 2026-07-20 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_student_created_at_student_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 20, 9, 10, 7, 294519)),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 20, 9, 10, 7, 295017)),
        ),
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
        migrations.AlterModelTable(
            name='subject',
            table='subjects',
        ),
    ]
